sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
    include:
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: nightly
    fast_finish: true

before_script:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --configuration phpunit.xml.dist --colors --coverage-clover=coverage.clover
  - test "5.6" == "${TRAVIS_PHP_VERSION}" && vendor/bin/docheader check library tests

after_script:
  - test "5.6" == "${TRAVIS_PHP_VERSION}" && wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
